# Numpy Exercise  <img src = "numpy1.png">
###### Authored by T.K.Senthil Kumar

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [1]:
#Solution
import numpy as np
numpy_array_1=np.random.randint(10, high=24, size=(24))
numpy_array_1

array([13, 11, 12, 21, 13, 23, 13, 22, 22, 15, 16, 15, 23, 11, 19, 20, 11,
       19, 16, 14, 21, 15, 17, 13])

#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [2]:
# Solution
numpy_array_2=np.arange(1, 50, step=2)
len(numpy_array_2)

25

#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [3]:
# Solution
numpy_array_3=np.linspace(4,7,27)
numpy_array_3

array([4.        , 4.11538462, 4.23076923, 4.34615385, 4.46153846,
       4.57692308, 4.69230769, 4.80769231, 4.92307692, 5.03846154,
       5.15384615, 5.26923077, 5.38461538, 5.5       , 5.61538462,
       5.73076923, 5.84615385, 5.96153846, 6.07692308, 6.19230769,
       6.30769231, 6.42307692, 6.53846154, 6.65384615, 6.76923077,
       6.88461538, 7.        ])

#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [4]:
# Solution
numpy_array_4=(100*np.random.sample(size=(5,4))).round(2)
numpy_array_4

array([[52.49, 67.6 , 52.29, 57.35],
       [ 2.48, 69.74,  5.57, 50.97],
       [81.09, 87.8 , 40.55, 91.57],
       [33.67, 12.53, 63.5 , 91.38],
       [84.6 , 69.86, 78.23, 79.74]])

#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [5]:
# Solution
numpy_array_5=np.random.randint(5, high=15, size=(5,5))
print('Numpy_array:\n',numpy_array_5)
print('Shape of numpy_array:',numpy_array_5.shape)

Numpy_array:
 [[ 9 12  6 13  9]
 [ 8  6 13 10 10]
 [11  5  5 12 11]
 [ 7  9 14 12  8]
 [ 5  5 13  7 12]]
Shape of numpy_array: (5, 5)


#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [6]:
# Solution
numpy_array_6=np.zeros(shape=np.random.randint(20),dtype='int32')

print('Numpy_array:',numpy_array_6)
print('Shape of numpy_array:',numpy_array_6.shape)
print('Datatype of numpy_array:',numpy_array_6.dtype)

Numpy_array: [0 0 0 0 0 0 0 0 0]
Shape of numpy_array: (9,)
Datatype of numpy_array: int32


#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [7]:
# Solution
#numpy_array_7=np.random.random_sample(size=(np.random.randint(20),np.random.randint(20)))*100
numpy_array_7=np.ones(shape=(np.random.randint(20),np.random.randint(20)),dtype='float32')
numpy_array_7

array([], shape=(0, 19), dtype=float32)

#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [8]:
# Solution
numpy_array_8=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
print('Shape of numpy_array:',numpy_array_8.shape)
print('Type of numpy_array:',type(numpy_array_8))
print('Datatype of numpy_array:',numpy_array_8.dtype)

Shape of numpy_array: (5, 5)
Type of numpy_array: <class 'numpy.ndarray'>
Datatype of numpy_array: int32


#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [9]:
#Solution
print('Centre pixel of the matrix:',numpy_array_8[int(numpy_array_8.shape[0]/2),int(numpy_array_8.shape[1]/2)])

Centre pixel of the matrix: 3


#### 10. Print the all the elements of 3rd row of the matrix

In [10]:
# Solution
print('3rd Row:', numpy_array_8[2])

3rd Row: [ 5  7  3 76  3]


#### 11. Print the all the elements of 4th columns of the matrix

In [11]:
# Solution
print('4th Column:', numpy_array_8[:,3])

4th Column: [34 65 76 54  5]


#### 12. Print the 4 corner pixels of the matrix

In [12]:
# Solution
print('4th corner pixel:', numpy_array_8[numpy_array_8.shape[0]-1,numpy_array_8.shape[1]-1])

4th corner pixel: 8


#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [13]:
# Solution
numpy_array_9=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
m1=numpy_array_9[:2,2:4]
m2=numpy_array_9[3:,:2]
m3=numpy_array_9[2:,2:]
print('m1:\n',m1)
print('\nm2:\n',m2)
print('\nm3:\n',m3)

m1:
 [[50 34]
 [34 65]]

m2:
 [[ 7  8]
 [23 12]]

m3:
 [[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]


#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [14]:
# Solution
print('Reshaped m1:',m1.flat[:])
print('Reshaped m2:',m2.flat[:])
print('Reshaped m3:',m3.flat[:])

Reshaped m1: [50 34 34 65]
Reshaped m2: [ 7  8 23 12]
Reshaped m3: [ 3 76  3  6 54  6  8  5  8]


#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [15]:
# Solution
print('Vertical matrix concatenation:\n',np.concatenate((m1,m2),axis=0))
print('\nHorizontal matrix concatenation:\n',np.concatenate((m1,m2),axis=1))

Vertical matrix concatenation:
 [[50 34]
 [34 65]
 [ 7  8]
 [23 12]]

Horizontal matrix concatenation:
 [[50 34  7  8]
 [34 65 23 12]]


#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [16]:
# Solution
print('Addition:\n',m1+m2)
print('\nSubtraction:\n',m1-m2)
print('\nMultiplicaton:\n',m1*m2)
print('\nDivision:\n',m1/m2)

Addition:
 [[57 42]
 [57 77]]

Subtraction:
 [[43 26]
 [11 53]]

Multiplicaton:
 [[350 272]
 [782 780]]

Division:
 [[7.14285714 4.25      ]
 [1.47826087 5.41666667]]


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [17]:
# Solution
print('Result:\n',m1+m3[:2,:2])

Result:
 [[ 53 110]
 [ 40 119]]


#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [18]:
# Solution
m4=np.concatenate((m1,np.mean(m1,axis=0).reshape(-1,2)),axis=0)
print('Resultant matrix:\n',m4)

Resultant matrix:
 [[50.  34. ]
 [34.  65. ]
 [42.  49.5]]


#### 19. Perform the matrix multiplication between m3 and m4

In [19]:
# Solution
print('m3 x m4:\n',np.matmul(m3,m4))

m3 x m4:
 [[2860.  5190.5]
 [2388.  4011. ]
 [ 906.   993. ]]


#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [20]:
# Solution
print('Max mean:',max(np.mean(numpy_array_8,axis=1)))
print('Min mean:',min(np.mean(numpy_array_8,axis=1)))
print('Max variance:',max(np.var(numpy_array_8,axis=1)))
print('Min variance:',min(np.var(numpy_array_8,axis=1)))
print('Max standard deviation:',max(np.std(numpy_array_8,axis=1)))
print('Min standard deviation:',min(np.std(numpy_array_8,axis=1)))

Max mean: 32.6
Min mean: 11.2
Max variance: 820.1600000000001
Min variance: 39.760000000000005
Max standard deviation: 28.63843571147
Min standard deviation: 6.305553108173779


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [21]:
# Solution 
runs=np.array([[54,60,10,65],[102,2,78,32],[3,110,1,92],[56,6,12,42],[12,8,22,11]])
runs_dic={'MSD':runs[0],'Kholi':runs[1],'Rohit':runs[2],'Rahul':runs[3],'Dhawan':runs[4]}

balls_faced=np.array([[50,42,22,78],[95,8,65,43],[9,100,7,101],[27,3,11,31],[24,20,36,27]])
balls_dic={'MSD':balls_faced[0],'Kholi':balls_faced[1],'Rohit':balls_faced[2],'Rahul':balls_faced[3],'Dhawan':balls_faced[4]}

runs_avg={}
for player,runs in runs_dic.items():
    runs_avg[player]=runs.mean()
    
strike_rate={}
for (player,balls),(player,runs) in zip(balls_dic.items(),runs_dic.items()):
    strike_rate[player]=round(runs.sum()*100/balls.sum(),2)
    
print(sorted(runs_avg.items(), key=lambda x: x[1],reverse=True))
print(sorted(strike_rate.items(), key=lambda x: x[1],reverse=True))

[('Kholi', 53.5), ('Rohit', 51.5), ('MSD', 47.25), ('Rahul', 29.0), ('Dhawan', 13.25)]
[('Rahul', 161.11), ('Kholi', 101.42), ('MSD', 98.44), ('Rohit', 94.93), ('Dhawan', 49.53)]


#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [22]:
# Solution
marks = np.array([65,84,47,56,89,98,48,77,80,39])

print('No. of students passed:',np.count_nonzero(marks>=50))
print('No. of students failed:',np.count_nonzero(marks<50))

No. of students passed: 7
No. of students failed: 3


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [23]:
# Solution
marks[((marks>=45)&(marks<=49))|(marks>80)] =marks[((marks>=45)&(marks<=49))|(marks>80)]+5
marks[marks>100]=100
print('Updated marks:',marks)

Updated marks: [ 65  89  52  56  94 100  53  77  80  39]


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [24]:
# Solution
import time
list_1=[x for x in range(1,60000)]
list_2=[y for y in range(1,60000)]

start_time=time.time()
result_list=[]
for x,y in zip(list_1,list_2):
    result_list.append((x**2+8)/y)
end_time=time.time()
print('List execution time in ms:',(end_time-start_time)*1000)

start_time_numpy=time.time()
numpy_list_1=np.array(list_1)
numpy_list_2=np.array(list_2)
numpy_result=((numpy_list_1**2)+8)/numpy_list_2
end_time_numpy=time.time()
print('Numpy execution time in ms:',(end_time_numpy-start_time_numpy)*1000)

List execution time in ms: 30.164241790771484
Numpy execution time in ms: 7.717609405517578


#### 25. Create a Github account and upload your solution with the short write-up on Numpy

In [25]:
# Solution
solutionURL='https://github.com/Ashwin-Baskar/Python/blob/main/Lab_Exercise_3/Numpy_Exercise-Batch8.ipynb'
print('Solution uploaded to',solutionURL)

url= 'https://raw.github.com/Ashwin-Baskar/Python/main/Numpy.txt'
import requests
page = requests.get(url)
print('\nShort write up on Numpy:\n',page.text,sep='')

Solution uploaded to https://github.com/Ashwin-Baskar/Python/blob/main/Lab_Exercise_3/Numpy_Exercise-Batch8.ipynb

Short write up on Numpy:
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance.

